"""Insert a real permanent archive identifier into the final thesis source.

This utility must be run only after the author has reserved or published an
authenticated DOI/permanent release. It never invents an identifier.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
THESIS = ROOT / "Thesis" / "Thesis.tex"
AUDIT = ROOT / "reviewer_data_audit"
BEGIN = "% BEGIN PERMANENT ARCHIVE IDENTIFIER"
END = "% END PERMANENT ARCHIVE IDENTIFIER"
BLOCKED = "BLOCKED_EXTERNAL_PUBLICATION"


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def tex_escape(value: str) -> str:
    replacements = {
        "\\": r"\textbackslash{}",
        "_": r"\_",
        "%": r"\%",
        "&": r"\&",
        "#": r"\#",
        "$": r"\$",
        "{": r"\{",
        "}": r"\}",
    }
    return "".join(replacements.get(character, character) for character in value)


def valid_identifier(value: str) -> bool:
    lowered = value.lower()
    if not value.strip() or BLOCKED.lower() in lowered:
        return False
    if re.fullmatch(r"(?:doi:|https://doi\.org/)?10\.\d{4,9}/\S+", value, re.I):
        return True
    return bool(re.fullmatch(r"https://\S+", value, re.I))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--archive-id", required=True)
    args = parser.parse_args()
    archive_id = args.archive_id.strip()
    if not valid_identifier(archive_id):
        raise ValueError(
            "The identifier must be a real DOI or stable HTTPS release URL; "
            "placeholders and BLOCKED_EXTERNAL_PUBLICATION are rejected."
        )
    if not THESIS.exists():
        raise FileNotFoundError(THESIS)
    text = THESIS.read_text(encoding="utf-8")
    pattern = re.compile(
        re.escape(BEGIN) + r".*?" + re.escape(END), flags=re.S
    )
    if len(pattern.findall(text)) != 1:
        raise ValueError("Expected exactly one permanent-identifier marker block")
    before = sha256(THESIS)
    replacement = (
        BEGIN + "\n"
        + r"\texttt{" + tex_escape(archive_id) + "}.\n"
        + END
    )
    updated = pattern.sub(lambda _: replacement, text, count=1)
    THESIS.write_text(updated, encoding="utf-8")
    archive_manifest = ROOT / "final_reviewer_closure" / "archive_manifest.json"
    record = {
        "created_utc": datetime.now(timezone.utc).isoformat(),
        "permanent_identifier": archive_id,
        "thesis_source": str(THESIS.resolve()),
        "thesis_sha256_before": before,
        "thesis_sha256_after": sha256(THESIS),
        "local_archive_manifest": (
            str(archive_manifest.resolve()) if archive_manifest.exists() else "DATA ABSENT"
        ),
        "local_archive_manifest_sha256": (
            sha256(archive_manifest) if archive_manifest.exists() else "DATA ABSENT"
        ),
        "note": (
            "Identifier supplied by the author after authenticated repository "
            "reservation/publication; it was not generated by the audit."
        ),
    }
    AUDIT.mkdir(parents=True, exist_ok=True)
    (AUDIT / "permanent_archive_identifier.json").write_text(
        json.dumps(record, indent=2), encoding="utf-8"
    )
    print(json.dumps(record, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
